# Generated by Django 4.2.5 on 2023-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('salary', models.FloatField(null=True)),
                ('city', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
