# Generated by Django 4.2.5 on 2023-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
