# Generated by Django 4.2.5 on 2023-11-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_table_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Table1',
        ),
    ]
