# Generated by Django 4.2.5 on 2023-11-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_table_table1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
