# Generated by Django 4.2.5 on 2023-11-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_person_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Person',
        ),
    ]
