# Generated by Django 4.2.5 on 2023-11-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_person_couser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ds',
            new_name='cname',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fs',
        ),
    ]
