# Generated by Django 4.2.5 on 2023-11-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Person',
            field=models.ForeignKey(default='full stack', on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
