# Generated by Django 4.2.5 on 2023-11-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_course_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
    ]
