# Generated by Django 4.2.5 on 2023-10-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_second'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Second',
        ),
    ]
