# Generated by Django 4.2.5 on 2023-11-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('cname', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
