# Generated by Django 4.2.5 on 2023-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_django_khalid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='django_khalid',
            name='gender',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
