# Generated by Django 4.2.5 on 2023-10-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_django_khalid_english_django_khalid_hindi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='django_khalid',
            name='city',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
