# Generated by Django 4.2.5 on 2023-12-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyntraCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('img1', models.ImageField(null=True, upload_to='myntra')),
                ('img2', models.ImageField(null=True, upload_to='myntra')),
                ('img3', models.ImageField(null=True, upload_to='myntra')),
                ('img4', models.ImageField(null=True, upload_to='myntra')),
            ],
        ),
    ]
